name: final
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        container: golang:1.24.1
        steps:
            - uses: actions/checkout@v4
            - name: Run Test
              run: GOOS=linux GOARCH=amd64 go test
            - name: Run Errors
              run: |
                go vet ./...
